### ISSUE TITLE
passing options to create commands

### ISSUE THREAD

**Issue by kav** [ChrisCates/rethink-config#4]
Starting to play with options passing. I've got:
```JSON
{
  "database": "peak",
  "tables": [
    "table",
    {
      "otherTable": {
        "primaryKey": "otherTableImportantNumber"
      }
    },
    "oneMoreTable"
  ]
}
```
in YAML
```YAML
database: peak
tables:
- table
- otherTable:
  primaryKey: otherTableImportantNumber
- oneMoreTable
```
Or as an alternative
```JSON
{
  "database": "peak",
  "tables": [
    "table",
    {
      "name": "otherTable",
      "primaryKey": "otherTableImportantNumber"
    },
    "oneMoreTable"
  ]
}
```
in YAML
```YAML
database: "peak"
tables: 
- "table"
- 
  name: "otherTable"
  primaryKey: "otherTableImportantNumber"
- "oneMoreTable"

```

I think I prefer the second case in JSON and the first in YAML. I'm inclined to go with the second if only because it prevents some strange edge cases. E.g. what happens when you have two root keys in the object, is that two different tables with configuration?

Will PR this shortly, just trying to be public as I work out my thinking
